# Generated by Django 3.1.7 on 2021-04-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0002_auto_20210412_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
